kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: zyfra-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32080
    hostPort: 8080
    protocol: TCP
  - containerPort: 32443
    hostPort: 8443
    protocol: TCP
  - containerPort: 32090
    hostPort: 9000
    protocol: TCP
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP
  - containerPort: 30083
    hostPort: 8083
    protocol: TCP
  - containerPort: 30084 #for postgres
    hostPort: 5432
    protocol: TCP
  - containerPort: 30085 #for minio
    hostPort: 9001
    protocol: TCP
  - containerPort: 30086 #for redis
    hostPort: 6379
    protocol: TCP
  - containerPort: 30087 #for grafana
    hostPort: 3001
    protocol: TCP
  extraMounts:                                                                                                                                                                                          
    - hostPath: /Users/nathansweb/mnt/data
      containerPath: /mnt/data
