apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotrue-api
  namespace: zyfra
  labels:
    app: gotrue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gotrue
  template:
    metadata:
      labels:
        app: gotrue
    spec:
      containers:
      - name: gotrue
        image: senthilsweb/gotrue:latest
        env:
          - name: GOTRUE_DB_DRIVER
            value: postgres
          - name: GOTRUE_API_PORT
            value: "3000"
          - name: API_EXTERNAL_URL
            value: http://gotrue-service:3000
          - name: DATABASE_URL
            value: postgres://zypress_user:zypress_pwd@18.189.3.157:5432/zypress_db
          - name: GOTRUE_JWT_SECRET
            value: "CHANGE-THIS! VERY IMPORTANT!"
          - name: GOTRUE_JWT_EXP
            value: "3600"
          - name: GOTRUE_JWT_AUD
            value: authenticated
          - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
            value: authenticated
          - name: GOTRUE_JWT_ADMIN_ROLES
            value: "supabase_admin,service_role"
          - name: GOTRUE_API_HOST
            value: 0.0.0.0
          - name: GOTRUE_SITE_URL
            value: "http://example.com"
          - name: GOTRUE_MAILER_AUTOCONFIRM
            value: true
          - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
            value: true
          - name: GOTRUE_SMTP_SENDER_NAME
            value: "John Smith"
          - name: GOTRUE_SMTP_HOST
            value: smtp.mailgun.org
          - name: GOTRUE_SMTP_PORT
            value: 587
          - name: GOTRUE_SMTP_USER
            value: 
          - name: GOTRUE_SMTP_PASS
            value: 
          - name: GOTRUE_SMTP_ADMIN_EMAIL
            value: 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: zyfra
  name: gotrue-service # this name will be used to resolve hostname between containers e.g. http://gotrue-service:3000
spec:
  ports:
  - name: http
    port: 3000        # Default port used by the image
    targetPort: 3000  # port exposed by Pod
  selector:
    app: gotrue       # points to the depoyment with the app named "gotrue" config
