apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-api
  namespace: zyfra
  labels:
    app: krakend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: senthilsweb/krakend:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: zyfra
  name: krakend-service # this name will be used to resolve hostname between containers e.g. http://krakend-service:3000
spec:
  ports:
  - name: http
    port: 8080        # Default port used by the image
    targetPort: 8080  # port exposed by Pod
  selector:
    app: krakend         # points to the depoyment with the app named "krakend" config
