apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-config
type: Opaque
data:
  password: cG9zdGdyZXMK
  redis_uri: ${{ secrets.REDIS_URI }}
  slack_token: ${{ secrets.SLACK_TOKEN }}
  slack_channel: ${{ secrets.SLACK_CHANNEL }}
