apiVersion: apps/v1
kind: Deployment
metadata:
  name: zygo-api
  namespace: zyfra
  labels:
    app: zygo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zygo
  template:
    metadata:
      labels:
        app: zygo
    spec:
      containers:
      - name: zygo
        image: senthilsweb/zygo:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 3000
