apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-api-server
  namespace: zypress-app
  labels:
    app: notifier-api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifier-api-server
  template:
    metadata:
      labels:
        app: notifier-api-server
    spec:
      containers:
      - name: notifier
        image: senthilsweb/zygo:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 3000
