apiVersion: v1
kind: Service
metadata:
  namespace: zypress-app
  labels:
    app: notifier-api-service
  name: notifier-api-service
spec:
  ports:
  - name: http
    port: 3000        # port exposed outside ClusterIP
    targetPort: 3000  # port exposed by Pod
  selector:
    app: notifier-api-server