apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifier-api-service
  name: notifier-api-service
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: notifier-api-server