apiVersion: v1
kind: Service
metadata:
  namespace: zypress-app
  labels:
    app: notifier-web-service
  name: notifier-web-service
spec:
  ports:
  - name: http
    port: 5000        # port exposed outside ClusterIP
    targetPort: 80  # port exposed by Pod
  selector:
    app: notifier-api-server