apiVersion: v1
kind: Service
metadata:
  namespace: zypress-app
  labels:
    app: notifier-web-service
  name: notifier-web-service
spec:
  ports:
  - name: http
    port: 3000        # port exposed outside ClusterIP
    targetPort: 3000  # port exposed by Pod (should match container port in the deployment manifest)
  selector:
    app: notifier-web-server