kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:                                                                                                                                                                                          
    - hostPath: /Users/nathansweb/mnt/data/www.gigref
      containerPath: /www
- role: worker
  extraMounts:                                                                                                                                                                                          
    - hostPath: /Users/nathansweb/mnt/data/www.gigref
      containerPath: /www