apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: notifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: senthilsweb/notifier:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-api
  name: nginx-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: notifier